name: fsof
description: 15 Seconds of Fame
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.3.0
  built_value_generator: ^8.3.0

  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4

  dash_kit_control_panel: ^3.0.4
  dash_kit_core: ^3.0.3
  dash_kit_network: ^3.1.1
  dash_kit_uikit: ^3.0.1

  extended_image: ^4.2.1

  firebase_analytics: 9.1.8
  firebase_core: ^1.17.0
  firebase_crashlytics: ^2.8.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2

  get_it: ^7.2.0
  golden_toolkit: ^0.10.0

  phone_number: ^0.12.0+2
  pin_code_fields: ^7.4.0
  preload_page_view: ^0.1.6

  rxdart: ^0.27.3

  shared_preferences: ^2.0.15

  video_player: ^2.4.2

  webview_flutter: ^3.0.4

  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.2.0
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/
    - assets/images/png/
    - assets/html/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700

