name: fsof
description: 15 Seconds of Fame
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.1.2
  built_value_generator: ^8.1.2

  cupertino_icons: ^1.0.3

  dash_kit_control_panel: ^3.0.1
  dash_kit_core: ^3.0.0
  dash_kit_network: ^3.0.1
  dash_kit_uikit: ^3.0.1

  extended_image: ^4.2.1

  firebase_analytics: 8.3.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0

  get_it: ^7.2.0
  golden_toolkit: ^0.10.0

  rxdart: ^0.27.2

  shared_preferences: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^5.0.1
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400

